### ISSUE TITLE
Sometimes "{event.target.href}" appears in the url

### ISSUE THREAD

**Issue by ottiker** [jillix/engine-ruut#5]
Tested wit the service public page. URL is sometimes changed to: `http://104.155.29.55:8000/%7Bevent.target.href%7D`.

**Comment by IonicaBizau** [comment]
This should be fixed with the correct CSS and HTML structure. That happens when you don't click the `<a>` element but it's parent (`li`, which was the padding).

This should be reported internally. :four_leaf_clover:

**Comment by lcristianiim** [comment]
It is true also for the private section.
